--Criação as tabelas

CREATE TABLE tb_mai_cidade (
    id_cidade VARCHAR2(5) NOT NULL,
    nm_cidade VARCHAR2(50) NOT NULL,
    id_estado VARCHAR2(5) NOT NULL
);

ALTER TABLE tb_mai_cidade ADD CONSTRAINT pk_mai_cidade PRIMARY KEY ( id_cidade );

CREATE TABLE tb_mai_empresa (
    id_empresa VARCHAR2(5) NOT NULL,
    nm_empresa VARCHAR2(30) NOT NULL,
    nr_cnpj    VARCHAR2(14) NOT NULL,
    ds_email   VARCHAR2(25) NOT NULL,
    id_login   VARCHAR2(5) NOT NULL,
    id_regiao  VARCHAR2(5) NOT NULL
);

ALTER TABLE tb_mai_empresa ADD CONSTRAINT pk_mai_empresa PRIMARY KEY ( id_empresa );

ALTER TABLE tb_mai_empresa ADD CONSTRAINT un_mai_empresa_cnpj UNIQUE ( nr_cnpj );

CREATE TABLE tb_mai_estado (
    id_estado VARCHAR2(5) NOT NULL,
    sg_estado CHAR(2) NOT NULL,
    nm_estado VARCHAR2(30) NOT NULL
);

ALTER TABLE tb_mai_estado ADD CONSTRAINT pk_mai_estado PRIMARY KEY ( id_estado );

CREATE TABLE tb_mai_login (
    id_login VARCHAR2(5) NOT NULL,
    ds_login VARCHAR2(30) NOT NULL,
    ds_senha VARCHAR2(20) NOT NULL,
    ds_salt  VARCHAR2(15) NOT NULL
);

ALTER TABLE tb_mai_login ADD CONSTRAINT pk_mai_usuario PRIMARY KEY ( id_login );

CREATE TABLE tb_mai_regiao (
    id_regiao VARCHAR2(5) NOT NULL,
    nm_regiao VARCHAR2(35) NOT NULL,
    id_cidade VARCHAR2(5) NOT NULL
);

ALTER TABLE tb_mai_regiao ADD CONSTRAINT pk_mai_regiao PRIMARY KEY ( id_regiao );

ALTER TABLE tb_mai_regiao
    ADD CONSTRAINT fk_mai_cidade FOREIGN KEY ( id_cidade )
        REFERENCES tb_mai_cidade ( id_cidade );

ALTER TABLE tb_mai_cidade
    ADD CONSTRAINT fk_mai_estado FOREIGN KEY ( id_estado )
        REFERENCES tb_mai_estado ( id_estado );

ALTER TABLE tb_mai_empresa
    ADD CONSTRAINT fk_mai_login FOREIGN KEY ( id_login )
        REFERENCES tb_mai_login ( id_login );

ALTER TABLE tb_mai_empresa
    ADD CONSTRAINT fk_mai_regiao_empresa FOREIGN KEY ( id_regiao )
        REFERENCES tb_mai_regiao ( id_regiao );

-- Exclusão das tabelas
DROP TABLE TB_MAI_CIDADE CASCADE CONSTRAINTS;
DROP TABLE TB_MAI_EMPRESA CASCADE CONSTRAINTS;
DROP TABLE TB_MAI_ESTADO CASCADE CONSTRAINTS;
DROP TABLE TB_MAI_LOGIN CASCADE CONSTRAINTS;
DROP TABLE TB_MAI_REGIAO CASCADE CONSTRAINTS;

--Inserindo nas tabelas

--Estado
INSERT INTO TB_MAI_ESTADO (ID_ESTADO, SG_ESTADO, NM_ESTADO)
VALUES (SQ_MAI_ESTADO.NEXTVAL, 'SP', 'Sao Paulo');

INSERT INTO TB_MAI_ESTADO (ID_ESTADO, SG_ESTADO, NM_ESTADO)
VALUES (SQ_MAI_ESTADO.NEXTVAL, 'RJ', 'Rio de Janeiro');

INSERT INTO TB_MAI_ESTADO (ID_ESTADO, SG_ESTADO, NM_ESTADO)
VALUES (SQ_MAI_ESTADO.NEXTVAL, 'AM', 'Amazonas');

INSERT INTO TB_MAI_ESTADO (ID_ESTADO, SG_ESTADO, NM_ESTADO)
VALUES (SQ_MAI_ESTADO.NEXTVAL, 'BA', 'Bahia');

INSERT INTO TB_MAI_ESTADO (ID_ESTADO, SG_ESTADO, NM_ESTADO)
VALUES (SQ_MAI_ESTADO.NEXTVAL, 'MG', 'Minas Gerais');

--Cidade

INSERT INTO TB_MAI_CIDADE (ID_CIDADE, NM_CIDADE, ID_ESTADO)
VALUES (SQ_MAI_CIDADE.NEXTVAL, 'São Paulo', 1);

INSERT INTO TB_MAI_CIDADE (ID_CIDADE, NM_CIDADE, ID_ESTADO)
VALUES (SQ_MAI_CIDADE.NEXTVAL, 'Rio de Janeiro', 2);

INSERT INTO TB_MAI_CIDADE (ID_CIDADE, NM_CIDADE, ID_ESTADO)
VALUES (SQ_MAI_CIDADE.NEXTVAL, 'Manaus', 3);

INSERT INTO TB_MAI_CIDADE (ID_CIDADE, NM_CIDADE, ID_ESTADO)
VALUES (SQ_MAI_CIDADE.NEXTVAL, 'Salvador', 4);

INSERT INTO TB_MAI_CIDADE (ID_CIDADE, NM_CIDADE, ID_ESTADO)
VALUES (SQ_MAI_CIDADE.NEXTVAL, 'Belo Horizonte', 5);

--Regiao

INSERT INTO TB_MAI_REGIAO (ID_REGIAO, NM_REGIAO, ID_CIDADE)
VALUES (SQ_MAI_REGIAO.NEXTVAL, 'SUL', 1);
    
INSERT INTO TB_MAI_REGIAO (ID_REGIAO, NM_REGIAO, ID_CIDADE)
VALUES (SQ_MAI_REGIAO.NEXTVAL, 'NORTE', 5);

INSERT INTO TB_MAI_REGIAO (ID_REGIAO, NM_REGIAO, ID_CIDADE)
VALUES (SQ_MAI_REGIAO.NEXTVAL, 'OESTE', 3);

INSERT INTO TB_MAI_REGIAO (ID_REGIAO, NM_REGIAO, ID_CIDADE)
VALUES (SQ_MAI_REGIAO.NEXTVAL, 'LESTE', 4);

INSERT INTO TB_MAI_REGIAO (ID_REGIAO, NM_REGIAO, ID_CIDADE)
VALUES (SQ_MAI_REGIAO.NEXTVAL, 'CENTRO', 2);

--Login

INSERT INTO TB_MAI_LOGIN (ID_LOGIN, DS_LOGIN, DS_SENHA, DS_SALT)
VALUES (SQ_MAI_LOGIN.NEXTVAL, 'sisley@gmail.com', 'transley38', 's54de2');

INSERT INTO TB_MAI_LOGIN (ID_LOGIN, DS_LOGIN, DS_SENHA, DS_SALT)
VALUES (SQ_MAI_LOGIN.NEXTVAL, 'zara@gmail.com', 'araz69', 'd63bl0');

INSERT INTO TB_MAI_LOGIN (ID_LOGIN, DS_LOGIN, DS_SENHA, DS_SALT)
VALUES (SQ_MAI_LOGIN.NEXTVAL, 'nike@gmail.com', 'ekin71', 'l84qa1');

--Empresa

INSERT INTO TB_MAI_EMPRESA (ID_EMPRESA, NM_EMPRESA, NR_CNPJ, DS_EMAIL, ID_LOGIN, ID_REGIAO)
VALUES (SQ_MAI_EMPRESA.NEXTVAL, 'Sisley', '48751652', 'sisley@gmail.com', 1, 5);

INSERT INTO TB_MAI_EMPRESA (ID_EMPRESA, NM_EMPRESA, NR_CNPJ, DS_EMAIL, ID_LOGIN, ID_REGIAO)
VALUES (SQ_MAI_EMPRESA.NEXTVAL, 'Zara', '02365478', 'zara@gmail.com', 2, 3);

INSERT INTO TB_MAI_EMPRESA (ID_EMPRESA, NM_EMPRESA, NR_CNPJ, DS_EMAIL, ID_LOGIN, ID_REGIAO)
VALUES (SQ_MAI_EMPRESA.NEXTVAL, 'Nike', '74589610', 'nike@gmail.com', 3, 2);